/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (bugfix_servletAD) -  4 Jan 2024 17:44
*/
#include <adStack.h>
#include <math.h>
double mass, massFrac, J11, J22, J00, grav, za;
double thr;
double thrb;
double a0, a1, a2, j0, j1, j2, s0, s1, s2, q0, q1, q2, dq0, dq1, dq2, ddq0, 
ddq1, ddq2, F, dF, ddF;
double a0b, a1b, a2b, j0b, j1b, j2b, s0b, s1b, s2b, q0b, q1b, q2b, dq0b, dq1b,
dq2b, ddq0b, ddq1b, ddq2b, Fb, dFb, ddFb;
double psi;
double quat0, quat1, quat2, quat3;
double quat0b, quat1b, quat2b, quat3b;
double omg0, omg1, omg2, domg0, domg1, domg2;
double omg0b, omg1b, omg2b, domg0b, domg1b, domg2b;
double z0, z1, z2, dz0, dz1, dz2, ddz0, ddz1, ddz2;
double z0b, z1b, z2b, dz0b, dz1b, dz2b, ddz0b, ddz1b, ddz2b;
double zu_sqr_norm, zu_norm, zu_norm3, zu_norm5, zu0, zu1, zu2, dzu0, dzu1, 
dzu2, ddzu0, ddzu1, ddzu2;
double zu_sqr_normb, zu_normb, zu_norm3b, zu_norm5b, zu0b, zu1b, zu2b, dzu0b, 
dzu1b, dzu2b, ddzu0b, ddzu1b, ddzu2b;
double tilt_den, tilt0, tilt1, tilt2, c_half_psi, s_half_psi;
double tilt_denb, tilt0b, tilt1b, tilt2b;
double c_psi, s_psi, omg_den;
double omg_denb;
double zudzu, zuddzu, dzudzu;
double zudzub, zuddzub, dzudzub;
double tau0, tau1, tau2;
double tau0b, tau1b, tau2b;
double R00, R01, R10, R11, R20, R21;
double R00b, R01b, R10b, R11b, R20b, R21b;

/*
  Differentiation of forward in reverse (adjoint) mode:
   gradient     of useful results: tau2 tau1 tau0 thr
   with respect to varying inputs: tau2 tau1 tau0 ddF dF F ddq2
                ddq1 ddq0 dq2 dq1 dq0 q2 q1 q0 s2 s1 s0 j2 j1
                j0 a2 a1 a0 thr
   RW status of diff variables: R21:(loc) R20:(loc) R11:(loc)
                R10:(loc) R01:(loc) R00:(loc) tau2:in-zero tau1:in-zero
                tau0:in-zero dzudzu:(loc) zuddzu:(loc) zudzu:(loc)
                omg_den:(loc) tilt2:(loc) tilt1:(loc) tilt0:(loc)
                tilt_den:(loc) ddzu2:(loc) ddzu1:(loc) ddzu0:(loc)
                dzu2:(loc) dzu1:(loc) dzu0:(loc) zu2:(loc) zu1:(loc)
                zu0:(loc) zu_norm5:(loc) zu_norm3:(loc) zu_norm:(loc)
                zu_sqr_norm:(loc) ddz2:(loc) ddz1:(loc) ddz0:(loc)
                dz2:(loc) dz1:(loc) dz0:(loc) z2:(loc) z1:(loc)
                z0:(loc) domg2:(loc) domg1:(loc) domg0:(loc) omg2:(loc)
                omg1:(loc) omg0:(loc) quat3:(loc) quat2:(loc)
                quat1:(loc) quat0:(loc) ddF:out dF:out F:out ddq2:out
                ddq1:out ddq0:out dq2:out dq1:out dq0:out q2:out
                q1:out q0:out s2:out s1:out s0:out j2:out j1:out
                j0:out a2:out a1:out a0:out thr:in-zero
*/
void forward_b() {
    double tempb;
    double temp;
    double tempb0;
    double temp0;
    double tempb1;
    zu0 = a0 + massFrac*F*q0;
    zu1 = a1 + massFrac*F*q1;
    zu2 = a2 + massFrac*F*q2 + grav;
    zu_sqr_norm = zu0*zu0 + zu1*zu1 + zu2*zu2;
    zu_norm = sqrt(zu_sqr_norm);
    z0 = zu0/zu_norm;
    z1 = zu1/zu_norm;
    z2 = zu2/zu_norm;
    zu_norm3 = zu_sqr_norm*zu_norm;
    zu_norm5 = zu_sqr_norm*zu_sqr_norm*zu_norm;
    dzu0 = j0 + massFrac*(F*dq0+dF*q0);
    dzu1 = j1 + massFrac*(F*dq1+dF*q1);
    dzu2 = j2 + massFrac*(F*dq2+dF*q2);
    ddzu0 = s0 + massFrac*(F*ddq0+2*dF*dq0+ddF*q0);
    ddzu1 = s1 + massFrac*(F*ddq1+2*dF*dq1+ddF*q1);
    ddzu2 = s2 + massFrac*(F*ddq2+2*dF*dq2+ddF*q2);
    zudzu = zu0*dzu0 + zu1*dzu1 + zu2*dzu2;
    dzudzu = dzu0*dzu0 + dzu1*dzu1 + dzu2*dzu2;
    zuddzu = zu0*ddzu0 + zu1*ddzu1 + zu2*ddzu2;
    dz0 = dzu0/zu_norm - zudzu*zu0/zu_norm3;
    dz1 = dzu1/zu_norm - zudzu*zu1/zu_norm3;
    dz2 = dzu2/zu_norm - zudzu*zu2/zu_norm3;
    ddz0 = ddzu0/zu_norm - ((dzudzu+zuddzu)*zu0+2*zudzu*dzu0)/zu_norm3 + 3*
        zudzu*zudzu*zu0/zu_norm5;
    ddz1 = ddzu1/zu_norm - ((dzudzu+zuddzu)*zu1+2*zudzu*dzu1)/zu_norm3 + 3*
        zudzu*zudzu*zu1/zu_norm5;
    ddz2 = ddzu2/zu_norm - ((dzudzu+zuddzu)*zu2+2*zudzu*dzu2)/zu_norm3 + 3*
        zudzu*zudzu*zu2/zu_norm5;
    tilt_den = sqrt(2.0*(1.0+z2));
    tilt0 = 0.5*tilt_den;
    tilt1 = -z1/tilt_den;
    tilt2 = z0/tilt_den;
    c_half_psi = cos(0.5*psi);
    s_half_psi = sin(0.5*psi);
    quat0 = tilt0*c_half_psi;
    quat1 = tilt1*c_half_psi + tilt2*s_half_psi;
    quat2 = tilt2*c_half_psi - tilt1*s_half_psi;
    quat3 = tilt0*s_half_psi;
    R00 = 1 - 2*quat2*quat2 - 2*quat3*quat3;
    R10 = 2*quat1*quat2 + 2*quat0*quat3;
    R20 = 2*quat1*quat3 - 2*quat0*quat2;
    R01 = 2*quat1*quat2 - 2*quat0*quat3;
    R11 = 1 - 2*quat1*quat1 - 2*quat3*quat3;
    R21 = 2*quat2*quat3 + 2*quat0*quat1;
    c_psi = cos(psi);
    s_psi = sin(psi);
    omg_den = z2 + 1.0;
    omg0 = dz0*s_psi - dz1*c_psi - dz2*(z0*s_psi-z1*c_psi)/omg_den;
    omg1 = dz0*c_psi + dz1*s_psi - dz2*(z0*c_psi+z1*s_psi)/omg_den;
    omg2 = (z1*dz0-z0*dz1)/omg_den;

    
    domg2b = J22*tau2b;
    omg1b = omg0*(J11-J00)*tau2b + omg2*(J22-J11)*tau0b;
    omg0b = omg1*(J11-J00)*tau2b + omg2*(J00-J22)*tau1b;
    domg1b = J11*tau1b;
    omg2b = omg0*(J00-J22)*tau1b + omg1*(J22-J11)*tau0b;
    tempb1 = F*za*tau1b;
    R00b = q0*tempb1;
    q0b = R00*tempb1;
    R10b = q1*tempb1;
    q1b = R10*tempb1;
    R20b = q2*tempb1;
    q2b = R20*tempb1;
    domg0b = J00*tau0b;
    tempb1 = -(F*za*tau0b);
    R01b = q0*tempb1;
    q0b = q0b + R01*tempb1;
    R11b = q1*tempb1;
    q1b = q1b + R11*tempb1;
    R21b = q2*tempb1;
    q2b = q2b + R21*tempb1;
    temp = dz2/(omg_den*omg_den);
    tempb1 = domg2b/omg_den;
    tempb = -(temp*domg2b);
    tempb0 = -((z1*dz0-z0*dz1)*domg2b/(omg_den*omg_den));
    dz2b = tempb0;
    omg_denb = -(2*omg_den*temp*tempb0) - (z1*ddz0-z0*ddz1)*tempb1/omg_den;
    z1b = dz0*tempb;
    dz0b = z1*tempb;
    z0b = -(dz1*tempb) - ddz1*tempb1;
    dz1b = -(z0*tempb);
    ddz0b = z1*tempb1 + c_psi*domg1b + s_psi*domg0b;
    ddz1b = s_psi*domg1b - z0*tempb1 - c_psi*domg0b;
    temp = dz2*dz2/(omg_den*omg_den);
    tempb0 = (c_psi*z0+s_psi*z1)*domg1b/(omg_den*omg_den);
    tempb = -(s_psi*domg1b/omg_den);
    z1b = z1b + ddz0*tempb1 + s_psi*temp*domg1b + ddz2*tempb;
    tempb1 = -(c_psi*domg1b/omg_den);
    ddz2b = z1*tempb;
    dz2b = dz2b + dz1*tempb + 2*dz2*tempb0 + dz0*tempb1;
    dz1b = dz1b + dz2*tempb;
    omg_denb = omg_denb - (ddz2*z1+dz2*dz1)*tempb/omg_den - 2*omg_den*temp*
        tempb0 - (ddz2*z0+dz2*dz0)*tempb1/omg_den;
    temp0 = dz2*dz2/(omg_den*omg_den);
    tempb0 = -(s_psi*domg0b/omg_den);
    z0b = z0b + c_psi*temp*domg1b + ddz2*tempb1 + s_psi*temp0*domg0b + ddz2*
        tempb0;
    dz0b = dz0b + dz2*tempb1 + dz2*tempb0;
    tempb = c_psi*domg0b/omg_den;
    ddz2b = ddz2b + z0*tempb1 + z1*tempb + z0*tempb0;
    tempb1 = (s_psi*z0-c_psi*z1)*domg0b/(omg_den*omg_den);
    dz2b = dz2b + 2*dz2*tempb1 + dz1*tempb + dz0*tempb0;
    omg_denb = omg_denb - 2*omg_den*temp0*tempb1 - (ddz2*z1+dz2*dz1)*tempb/
        omg_den - (ddz2*z0+dz2*dz0)*tempb0/omg_den;
    tempb0 = omg2b/omg_den;
    dz1b = dz1b + dz2*tempb + s_psi*omg1b - z0*tempb0 - c_psi*omg0b;
    dz0b = dz0b + z1*tempb0 + c_psi*omg1b + s_psi*omg0b;
    omg_denb = omg_denb - (z1*dz0-z0*dz1)*tempb0/omg_den;
    temp = dz2/omg_den;
    z1b = z1b + ddz2*tempb - c_psi*temp0*domg0b + dz0*tempb0 - s_psi*temp*
        omg1b;
    z0b = z0b - dz1*tempb0 - c_psi*temp*omg1b;
    tempb0 = -((c_psi*z0+s_psi*z1)*omg1b/omg_den);
    dz2b = dz2b + tempb0;
    omg_denb = omg_denb - temp*tempb0;
    temp = dz2/omg_den;
    tempb0 = -((s_psi*z0-c_psi*z1)*omg0b/omg_den);
    dz2b = dz2b + tempb0;
    omg_denb = omg_denb - temp*tempb0;
    quat2b = 2*quat3*R21b + 2*quat1*R01b + 2*quat1*R10b - 2*quat0*R20b - 2*2*
        quat2*R00b;
    quat3b = 2*quat2*R21b + 2*quat1*R20b - 2*2*quat3*R11b - 2*quat0*R01b + 2*
        quat0*R10b - 2*2*quat3*R00b;
    quat0b = 2*quat1*R21b + 2*quat3*R10b - 2*quat3*R01b - 2*quat2*R20b;
    quat1b = 2*quat0*R21b + 2*quat2*R01b - 2*2*quat1*R11b + 2*quat3*R20b + 2*
        quat2*R10b;
    tilt0b = s_half_psi*quat3b + c_half_psi*quat0b;
    tilt2b = c_half_psi*quat2b + s_half_psi*quat1b;
    z0b = z0b + tilt2b/tilt_den - s_psi*temp*omg0b;
    tilt1b = c_half_psi*quat1b - s_half_psi*quat2b;
    z1b = z1b + c_psi*temp*omg0b - tilt1b/tilt_den;
    tilt_denb = z1*tilt1b/(tilt_den*tilt_den) - z0*tilt2b/(tilt_den*tilt_den) 
        + 0.5*tilt0b;
    z2b = (2.0*(z2+1.0) == 0.0 ? omg_denb : omg_denb + tilt_denb/sqrt(2.0*(z2+
        1.0)));
    tempb0 = -(ddz2b/zu_norm3);
    zudzub = 2*zudzu*3*zu2*ddz2b/zu_norm5 + 2*dzu2*tempb0;
    tempb = 3*(zudzu*zudzu)*ddz2b/zu_norm5;
    zu2b = tempb + (dzudzu+zuddzu)*tempb0;
    zu_norm5b = -(zu2*tempb/zu_norm5);
    dzudzub = zu2*tempb0;
    zuddzub = zu2*tempb0;
    dzu2b = 2*zudzu*tempb0;
    zu_norm3b = -(((dzudzu+zuddzu)*zu2+2*zudzu*dzu2)*tempb0/zu_norm3);
    tempb0 = -(ddz1b/zu_norm3);
    tempb = 3*(zudzu*zudzu)*ddz1b/zu_norm5;
    zu1b = tempb + (dzudzu+zuddzu)*tempb0;
    zu_norm5b = zu_norm5b - zu1*tempb/zu_norm5;
    dzu1b = 2*zudzu*tempb0;
    tempb = -(ddz0b/zu_norm3);
    zudzub = zudzub + 2*zudzu*3*zu1*ddz1b/zu_norm5 + 2*dzu1*tempb0 + 2*zudzu*3
        *zu0*ddz0b/zu_norm5 + 2*dzu0*tempb;
    dzudzub = dzudzub + zu1*tempb0 + zu0*tempb;
    zuddzub = zuddzub + zu1*tempb0 + zu0*tempb;
    ddzu2b = ddz2b/zu_norm + zu2*zuddzub;
    ddzu1b = ddz1b/zu_norm + zu1*zuddzub;
    zu_norm3b = zu_norm3b - ((dzudzu+zuddzu)*zu1+2*zudzu*dzu1)*tempb0/zu_norm3
        - ((dzudzu+zuddzu)*zu0+2*zudzu*dzu0)*tempb/zu_norm3;
    ddzu0b = ddz0b/zu_norm + zu0*zuddzub;
    tempb0 = 3*(zudzu*zudzu)*ddz0b/zu_norm5;
    zu0b = tempb0 + (dzudzu+zuddzu)*tempb;
    zu_norm5b = zu_norm5b - zu0*tempb0/zu_norm5;
    dzu0b = 2*zudzu*tempb;
    tempb = -(dz2b/zu_norm3);
    zudzub = zudzub + zu2*tempb;
    zu2b = zu2b + zudzu*tempb;
    zu_norm3b = zu_norm3b - zudzu*zu2*tempb/zu_norm3;
    tempb = -(dz1b/zu_norm3);
    zudzub = zudzub + zu1*tempb;
    zu1b = zu1b + zudzu*tempb;
    zu_norm3b = zu_norm3b - zudzu*zu1*tempb/zu_norm3;
    tempb = -(dz0b/zu_norm3);
    zudzub = zudzub + zu0*tempb;
    dzu2b = dzu2b + dz2b/zu_norm + 2*dzu2*dzudzub + zu2*zudzub;
    dzu1b = dzu1b + dz1b/zu_norm + 2*dzu1*dzudzub + zu1*zudzub;
    dzu0b = dzu0b + dz0b/zu_norm + 2*dzu0*dzudzub + zu0*zudzub;
    zu_norm3b = zu_norm3b - zudzu*zu0*tempb/zu_norm3;
    zu_normb = mass*thrb + zu_sqr_norm*zu_sqr_norm*zu_norm5b - ddzu2*ddz2b/(
        zu_norm*zu_norm) - ddzu1*ddz1b/(zu_norm*zu_norm) - ddzu0*ddz0b/(
        zu_norm*zu_norm) - dzu2*dz2b/(zu_norm*zu_norm) - dzu1*dz1b/(zu_norm*
        zu_norm) - dzu0*dz0b/(zu_norm*zu_norm) + zu_sqr_norm*zu_norm3b - zu2*
        z2b/(zu_norm*zu_norm) - zu1*z1b/(zu_norm*zu_norm) - zu0*z0b/(zu_norm*
        zu_norm);
    s2b = ddzu2b;
    s1b = ddzu1b;
    s0b = ddzu0b;
    j2b = dzu2b;
    j1b = dzu1b;
    j0b = dzu0b;
    zu_sqr_normb = (zu_sqr_norm == 0.0 ? 2*zu_sqr_norm*zu_norm*zu_norm5b + 
        zu_norm*zu_norm3b : 2*zu_sqr_norm*zu_norm*zu_norm5b + zu_norm*
        zu_norm3b + zu_normb/(2.0*sqrt(zu_sqr_norm)));
    zu0b = zu0b + zudzu*tempb + ddzu0*zuddzub + dzu0*zudzub + z0b/zu_norm + 2*
        zu0*zu_sqr_normb;
    zu1b = zu1b + ddzu1*zuddzub + dzu1*zudzub + z1b/zu_norm + 2*zu1*
        zu_sqr_normb;
    zu2b = zu2b + ddzu2*zuddzub + dzu2*zudzub + z2b/zu_norm + 2*zu2*
        zu_sqr_normb;
    tempb = massFrac*ddzu2b;
    Fb = (R00*q0+R10*q1+R20*q2)*za*tau1b + ddq2*tempb - (R01*q0+R11*q1+R21*q2)
        *za*tau0b;
    ddq2b = F*tempb;
    dFb = 2*dq2*tempb;
    dq2b = 2*dF*tempb;
    ddFb = q2*tempb;
    q2b = q2b + ddF*tempb;
    tempb = massFrac*ddzu1b;
    Fb = Fb + ddq1*tempb;
    ddq1b = F*tempb;
    dFb = dFb + 2*dq1*tempb;
    dq1b = 2*dF*tempb;
    ddFb = ddFb + q1*tempb;
    q1b = q1b + ddF*tempb;
    tempb = massFrac*ddzu0b;
    Fb = Fb + ddq0*tempb;
    ddq0b = F*tempb;
    dFb = dFb + 2*dq0*tempb;
    dq0b = 2*dF*tempb;
    ddFb = ddFb + q0*tempb;
    q0b = q0b + ddF*tempb;
    tempb = massFrac*dzu2b;
    Fb = Fb + dq2*tempb;
    dq2b = dq2b + F*tempb;
    dFb = dFb + q2*tempb;
    q2b = q2b + dF*tempb + F*massFrac*zu2b;
    tempb = massFrac*dzu1b;
    Fb = Fb + dq1*tempb;
    dq1b = dq1b + F*tempb;
    dFb = dFb + q1*tempb;
    q1b = q1b + dF*tempb + F*massFrac*zu1b;
    tempb = massFrac*dzu0b;
    Fb = Fb + dq0*tempb + q2*massFrac*zu2b + q1*massFrac*zu1b + q0*massFrac*
        zu0b;
    dq0b = dq0b + F*tempb;
    dFb = dFb + q0*tempb;
    q0b = q0b + dF*tempb + F*massFrac*zu0b;
    a2b = zu2b;
    a1b = zu1b;
    a0b = zu0b;
    tau2b = 0.0;
    tau1b = 0.0;
    tau0b = 0.0;
    thrb = 0.0;
}
